kind: Secret
apiVersion: v1
metadata:
    name: game-library-auth-dbconfig
    namespace: game-library
data:
    DB_DSN: {{echo db_dsn | base64}}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
    name: token-cert
    namespace: game-library
data:
    private: {{cat private.pem | base64 -w 0}}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
    name: game-library-auth
    namespace: game-library
data:
    AUTH_GOOGLECLIENTID: {{echo google_client_id | base64}}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
    name: game-library-auth-email-sender
    namespace: game-library
data:
    EMAIL_SENDER_API_TOKEN: {{echo email_sender_api_token | base64}}
type: Opaque
