// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/grpc/authapi/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/grpc/authapi/service.go -destination=internal/api/grpc/authapi/mocks/auth_facade.go -package=authapi_mocks
//

// Package authapi_mocks is a generated GoMock package.
package authapi_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthFacade is a mock of AuthFacade interface.
type MockAuthFacade struct {
	ctrl     *gomock.Controller
	recorder *MockAuthFacadeMockRecorder
	isgomock struct{}
}

// MockAuthFacadeMockRecorder is the mock recorder for MockAuthFacade.
type MockAuthFacadeMockRecorder struct {
	mock *MockAuthFacade
}

// NewMockAuthFacade creates a new mock instance.
func NewMockAuthFacade(ctrl *gomock.Controller) *MockAuthFacade {
	mock := &MockAuthFacade{ctrl: ctrl}
	mock.recorder = &MockAuthFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthFacade) EXPECT() *MockAuthFacadeMockRecorder {
	return m.recorder
}

// ValidateAccessToken mocks base method.
func (m *MockAuthFacade) ValidateAccessToken(tokenStr string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenStr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockAuthFacadeMockRecorder) ValidateAccessToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockAuthFacade)(nil).ValidateAccessToken), tokenStr)
}
