# Options for analysis running.
run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 3m

# All available settings of specific linters.
linters-settings:
  errcheck:
    # List of functions to exclude from checking, where each entry is a single function to exclude.
    # See https://github.com/kisielk/errcheck#excluding-functions for details.
    exclude-functions:
  goconst:
    min-len: 3
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - gosimple
    - unused
    - revive
    - typecheck
    - shadow

issues:
  exclude:
    # pprof exposure. closed with auth
    - G108

  # Which dirs to skip: issues from them won't be reported.
  # Can use regexp here: `generated.*`, regexp is applied on full path.
  exclude-dirs:
    - docs
