// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: infoapi/v1/infoapi.proto

package infoapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InfoApiService_CompanyExists_FullMethodName = "/infoapi.v1.InfoApiService/CompanyExists"
)

// InfoApiServiceClient is the client API for InfoApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InfoApiServiceClient interface {
	// CompanyExists checks if a company with the given name exists in IGDB (case-insensitive)
	CompanyExists(ctx context.Context, in *CompanyExistsRequest, opts ...grpc.CallOption) (*CompanyExistsResponse, error)
}

type infoApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoApiServiceClient(cc grpc.ClientConnInterface) InfoApiServiceClient {
	return &infoApiServiceClient{cc}
}

func (c *infoApiServiceClient) CompanyExists(ctx context.Context, in *CompanyExistsRequest, opts ...grpc.CallOption) (*CompanyExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanyExistsResponse)
	err := c.cc.Invoke(ctx, InfoApiService_CompanyExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoApiServiceServer is the server API for InfoApiService service.
// All implementations must embed UnimplementedInfoApiServiceServer
// for forward compatibility.
type InfoApiServiceServer interface {
	// CompanyExists checks if a company with the given name exists in IGDB (case-insensitive)
	CompanyExists(context.Context, *CompanyExistsRequest) (*CompanyExistsResponse, error)
	mustEmbedUnimplementedInfoApiServiceServer()
}

// UnimplementedInfoApiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInfoApiServiceServer struct{}

func (UnimplementedInfoApiServiceServer) CompanyExists(context.Context, *CompanyExistsRequest) (*CompanyExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompanyExists not implemented")
}
func (UnimplementedInfoApiServiceServer) mustEmbedUnimplementedInfoApiServiceServer() {}
func (UnimplementedInfoApiServiceServer) testEmbeddedByValue()                        {}

// UnsafeInfoApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfoApiServiceServer will
// result in compilation errors.
type UnsafeInfoApiServiceServer interface {
	mustEmbedUnimplementedInfoApiServiceServer()
}

func RegisterInfoApiServiceServer(s grpc.ServiceRegistrar, srv InfoApiServiceServer) {
	// If the following call pancis, it indicates UnimplementedInfoApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InfoApiService_ServiceDesc, srv)
}

func _InfoApiService_CompanyExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoApiServiceServer).CompanyExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoApiService_CompanyExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoApiServiceServer).CompanyExists(ctx, req.(*CompanyExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InfoApiService_ServiceDesc is the grpc.ServiceDesc for InfoApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InfoApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infoapi.v1.InfoApiService",
	HandlerType: (*InfoApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompanyExists",
			Handler:    _InfoApiService_CompanyExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infoapi/v1/infoapi.proto",
}
