// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: infoapi/v1/infoapi.proto

package infoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanyExistsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CompanyName *string                `protobuf:"bytes,1,opt,name=company_name,json=companyName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CompanyExistsRequest) Reset() {
	*x = CompanyExistsRequest{}
	mi := &file_infoapi_v1_infoapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyExistsRequest) ProtoMessage() {}

func (x *CompanyExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infoapi_v1_infoapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompanyExistsRequest) GetCompanyName() string {
	if x != nil {
		if x.xxx_hidden_CompanyName != nil {
			return *x.xxx_hidden_CompanyName
		}
		return ""
	}
	return ""
}

func (x *CompanyExistsRequest) SetCompanyName(v string) {
	x.xxx_hidden_CompanyName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CompanyExistsRequest) HasCompanyName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CompanyExistsRequest) ClearCompanyName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CompanyName = nil
}

type CompanyExistsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CompanyName *string
}

func (b0 CompanyExistsRequest_builder) Build() *CompanyExistsRequest {
	m0 := &CompanyExistsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CompanyName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_CompanyName = b.CompanyName
	}
	return m0
}

type CompanyExistsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Exists      bool                   `protobuf:"varint,1,opt,name=exists"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CompanyExistsResponse) Reset() {
	*x = CompanyExistsResponse{}
	mi := &file_infoapi_v1_infoapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyExistsResponse) ProtoMessage() {}

func (x *CompanyExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infoapi_v1_infoapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompanyExistsResponse) GetExists() bool {
	if x != nil {
		return x.xxx_hidden_Exists
	}
	return false
}

func (x *CompanyExistsResponse) SetExists(v bool) {
	x.xxx_hidden_Exists = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CompanyExistsResponse) HasExists() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CompanyExistsResponse) ClearExists() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Exists = false
}

type CompanyExistsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Exists *bool
}

func (b0 CompanyExistsResponse_builder) Build() *CompanyExistsResponse {
	m0 := &CompanyExistsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Exists != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Exists = *b.Exists
	}
	return m0
}

var File_infoapi_v1_infoapi_proto protoreflect.FileDescriptor

const file_infoapi_v1_infoapi_proto_rawDesc = "" +
	"\n" +
	"\x18infoapi/v1/infoapi.proto\x12\n" +
	"infoapi.v1\x1a!google/protobuf/go_features.proto\"9\n" +
	"\x14CompanyExistsRequest\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\"/\n" +
	"\x15CompanyExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2f\n" +
	"\x0eInfoApiService\x12T\n" +
	"\rCompanyExists\x12 .infoapi.v1.CompanyExistsRequest\x1a!.infoapi.v1.CompanyExistsResponseBFZ<github.com/OutOfStack/game-library/pkg/proto/infoapi;infoapi\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_infoapi_v1_infoapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_infoapi_v1_infoapi_proto_goTypes = []any{
	(*CompanyExistsRequest)(nil),  // 0: infoapi.v1.CompanyExistsRequest
	(*CompanyExistsResponse)(nil), // 1: infoapi.v1.CompanyExistsResponse
}
var file_infoapi_v1_infoapi_proto_depIdxs = []int32{
	0, // 0: infoapi.v1.InfoApiService.CompanyExists:input_type -> infoapi.v1.CompanyExistsRequest
	1, // 1: infoapi.v1.InfoApiService.CompanyExists:output_type -> infoapi.v1.CompanyExistsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infoapi_v1_infoapi_proto_init() }
func file_infoapi_v1_infoapi_proto_init() {
	if File_infoapi_v1_infoapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infoapi_v1_infoapi_proto_rawDesc), len(file_infoapi_v1_infoapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infoapi_v1_infoapi_proto_goTypes,
		DependencyIndexes: file_infoapi_v1_infoapi_proto_depIdxs,
		MessageInfos:      file_infoapi_v1_infoapi_proto_msgTypes,
	}.Build()
	File_infoapi_v1_infoapi_proto = out.File
	file_infoapi_v1_infoapi_proto_goTypes = nil
	file_infoapi_v1_infoapi_proto_depIdxs = nil
}
