kind: ConfigMap
apiVersion: v1
metadata:
    name: game-library-auth-config
    namespace: game-library
data:
    APP_ADDRESS: 0.0.0.0:8000
    DEBUG_ADDRESS: 0.0.0.0:6060
    APP_ALLOWEDCORSORIGIN: https://vmi644117.contaboserver.net
    AUTH_PRIVATEKEYFILE: /etc/gla/private
    AUTH_ISSUER: https://vmi644117.contaboserver.net
