kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
    name: game-library-auth-ingress
    namespace: game-library
    annotations:
        ingressclass.kubernetes.io/is-default-class: 'true'
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
    rules:
      - host: vmi644117.contaboserver.net
        http:
            paths:
              - path: /_auth(/|$)(.*)
                pathType: Prefix
                backend:
                    service:
                        name: game-library-auth-service
                        port:
                            number: 8000
              - path: /_debug/auth(/|$)(.*)
                pathType: Prefix
                backend:
                    service:
                        name: game-library-auth-service
                        port:
                            number: 6060
