POST http://localhost:8001/signup
Content-Type: application/json

{
  "username": "test_user",
  "name": "Test User",
  "password": "password",
  "confirmPassword": "password",
  "isPublisher": false
}

###
