POST http://localhost:8001/signup
Content-Type: application/json

{
  "username": "test_user",
  "name": "Test User",
  "password": "123456qwe",
  "confirmPassword": "123456qwe",
  "isPublisher": false
}

###
