// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/unsubscribe/api.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/unsubscribe/api.go -destination=internal/api/unsubscribe/mocks/api.go -package=unsubscribe_mocks
//

// Package unsubscribe_mocks is a generated GoMock package.
package unsubscribe_mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFacade is a mock of Facade interface.
type MockFacade struct {
	ctrl     *gomock.Controller
	recorder *MockFacadeMockRecorder
	isgomock struct{}
}

// MockFacadeMockRecorder is the mock recorder for MockFacade.
type MockFacadeMockRecorder struct {
	mock *MockFacade
}

// NewMockFacade creates a new mock instance.
func NewMockFacade(ctrl *gomock.Controller) *MockFacade {
	mock := &MockFacade{ctrl: ctrl}
	mock.recorder = &MockFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacade) EXPECT() *MockFacadeMockRecorder {
	return m.recorder
}

// IsEmailUnsubscribed mocks base method.
func (m *MockFacade) IsEmailUnsubscribed(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmailUnsubscribed", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEmailUnsubscribed indicates an expected call of IsEmailUnsubscribed.
func (mr *MockFacadeMockRecorder) IsEmailUnsubscribed(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmailUnsubscribed", reflect.TypeOf((*MockFacade)(nil).IsEmailUnsubscribed), ctx, email)
}

// UnsubscribeEmail mocks base method.
func (m *MockFacade) UnsubscribeEmail(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeEmail", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsubscribeEmail indicates an expected call of UnsubscribeEmail.
func (mr *MockFacadeMockRecorder) UnsubscribeEmail(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeEmail", reflect.TypeOf((*MockFacade)(nil).UnsubscribeEmail), ctx, token)
}
