// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gofiber/fiber/v2 (interfaces: Views)
//
// Generated by this command:
//
//	mockgen -destination=internal/api/unsubscribe/mocks/views.go -package=unsubscribe_mocks github.com/gofiber/fiber/v2 Views
//

// Package unsubscribe_mocks is a generated GoMock package.
package unsubscribe_mocks

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockViews is a mock of Views interface.
type MockViews struct {
	ctrl     *gomock.Controller
	recorder *MockViewsMockRecorder
	isgomock struct{}
}

// MockViewsMockRecorder is the mock recorder for MockViews.
type MockViewsMockRecorder struct {
	mock *MockViews
}

// NewMockViews creates a new mock instance.
func NewMockViews(ctrl *gomock.Controller) *MockViews {
	mock := &MockViews{ctrl: ctrl}
	mock.recorder = &MockViewsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViews) EXPECT() *MockViewsMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockViews) Load() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockViewsMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockViews)(nil).Load))
}

// Render mocks base method.
func (m *MockViews) Render(arg0 io.Writer, arg1 string, arg2 any, arg3 ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Render", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockViewsMockRecorder) Render(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockViews)(nil).Render), varargs...)
}
