// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handlers/auth.go
//
// Generated by this command:
//
//	mockgen -source=internal/handlers/auth.go -destination=internal/handlers/mocks/auth.go -package=handlers_mocks
//

// Package handlers_mocks is a generated GoMock package.
package handlers_mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/OutOfStack/game-library-auth/internal/auth"
	database "github.com/OutOfStack/game-library-auth/internal/database"
	jwt "github.com/golang-jwt/jwt/v4"
	gomock "go.uber.org/mock/gomock"
	idtoken "google.golang.org/api/idtoken"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CheckUserExists mocks base method.
func (m *MockStorage) CheckUserExists(ctx context.Context, name string, role database.Role) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExists", ctx, name, role)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserExists indicates an expected call of CheckUserExists.
func (mr *MockStorageMockRecorder) CheckUserExists(ctx, name, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExists", reflect.TypeOf((*MockStorage)(nil).CheckUserExists), ctx, name, role)
}

// CreateUser mocks base method.
func (m *MockStorage) CreateUser(ctx context.Context, user database.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStorageMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStorage)(nil).CreateUser), ctx, user)
}

// GetUserByID mocks base method.
func (m *MockStorage) GetUserByID(ctx context.Context, userID string) (database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStorageMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStorage)(nil).GetUserByID), ctx, userID)
}

// GetUserByOAuth mocks base method.
func (m *MockStorage) GetUserByOAuth(ctx context.Context, provider, oauthID string) (database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByOAuth", ctx, provider, oauthID)
	ret0, _ := ret[0].(database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByOAuth indicates an expected call of GetUserByOAuth.
func (mr *MockStorageMockRecorder) GetUserByOAuth(ctx, provider, oauthID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByOAuth", reflect.TypeOf((*MockStorage)(nil).GetUserByOAuth), ctx, provider, oauthID)
}

// GetUserByUsername mocks base method.
func (m *MockStorage) GetUserByUsername(ctx context.Context, username string) (database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStorageMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStorage)(nil).GetUserByUsername), ctx, username)
}

// UpdateUser mocks base method.
func (m *MockStorage) UpdateUser(ctx context.Context, user database.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStorageMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStorage)(nil).UpdateUser), ctx, user)
}

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
	isgomock struct{}
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// CreateClaims mocks base method.
func (m *MockAuth) CreateClaims(user database.User) jwt.Claims {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClaims", user)
	ret0, _ := ret[0].(jwt.Claims)
	return ret0
}

// CreateClaims indicates an expected call of CreateClaims.
func (mr *MockAuthMockRecorder) CreateClaims(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClaims", reflect.TypeOf((*MockAuth)(nil).CreateClaims), user)
}

// GenerateToken mocks base method.
func (m *MockAuth) GenerateToken(claims jwt.Claims) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", claims)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockAuthMockRecorder) GenerateToken(claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockAuth)(nil).GenerateToken), claims)
}

// ValidateToken mocks base method.
func (m *MockAuth) ValidateToken(tokenStr string) (auth.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenStr)
	ret0, _ := ret[0].(auth.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAuthMockRecorder) ValidateToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAuth)(nil).ValidateToken), tokenStr)
}

// MockGoogleTokenValidator is a mock of GoogleTokenValidator interface.
type MockGoogleTokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleTokenValidatorMockRecorder
	isgomock struct{}
}

// MockGoogleTokenValidatorMockRecorder is the mock recorder for MockGoogleTokenValidator.
type MockGoogleTokenValidatorMockRecorder struct {
	mock *MockGoogleTokenValidator
}

// NewMockGoogleTokenValidator creates a new mock instance.
func NewMockGoogleTokenValidator(ctrl *gomock.Controller) *MockGoogleTokenValidator {
	mock := &MockGoogleTokenValidator{ctrl: ctrl}
	mock.recorder = &MockGoogleTokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleTokenValidator) EXPECT() *MockGoogleTokenValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockGoogleTokenValidator) Validate(ctx context.Context, idToken, audience string) (*idtoken.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, idToken, audience)
	ret0, _ := ret[0].(*idtoken.Payload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockGoogleTokenValidatorMockRecorder) Validate(ctx, idToken, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockGoogleTokenValidator)(nil).Validate), ctx, idToken, audience)
}
