// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handlers/auth.go
//
// Generated by this command:
//
//	mockgen -source=internal/handlers/auth.go -destination=internal/handlers/mocks/auth.go -package=handlers_mocks
//

// Package handlers_mocks is a generated GoMock package.
package handlers_mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/OutOfStack/game-library-auth/internal/auth"
	facade "github.com/OutOfStack/game-library-auth/internal/facade"
	model "github.com/OutOfStack/game-library-auth/internal/model"
	gomock "go.uber.org/mock/gomock"
	idtoken "google.golang.org/api/idtoken"
)

// MockGoogleTokenValidator is a mock of GoogleTokenValidator interface.
type MockGoogleTokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleTokenValidatorMockRecorder
	isgomock struct{}
}

// MockGoogleTokenValidatorMockRecorder is the mock recorder for MockGoogleTokenValidator.
type MockGoogleTokenValidatorMockRecorder struct {
	mock *MockGoogleTokenValidator
}

// NewMockGoogleTokenValidator creates a new mock instance.
func NewMockGoogleTokenValidator(ctrl *gomock.Controller) *MockGoogleTokenValidator {
	mock := &MockGoogleTokenValidator{ctrl: ctrl}
	mock.recorder = &MockGoogleTokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleTokenValidator) EXPECT() *MockGoogleTokenValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockGoogleTokenValidator) Validate(ctx context.Context, idToken, audience string) (*idtoken.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, idToken, audience)
	ret0, _ := ret[0].(*idtoken.Payload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockGoogleTokenValidatorMockRecorder) Validate(ctx, idToken, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockGoogleTokenValidator)(nil).Validate), ctx, idToken, audience)
}

// MockUserFacade is a mock of UserFacade interface.
type MockUserFacade struct {
	ctrl     *gomock.Controller
	recorder *MockUserFacadeMockRecorder
	isgomock struct{}
}

// MockUserFacadeMockRecorder is the mock recorder for MockUserFacade.
type MockUserFacadeMockRecorder struct {
	mock *MockUserFacade
}

// NewMockUserFacade creates a new mock instance.
func NewMockUserFacade(ctrl *gomock.Controller) *MockUserFacade {
	mock := &MockUserFacade{ctrl: ctrl}
	mock.recorder = &MockUserFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFacade) EXPECT() *MockUserFacadeMockRecorder {
	return m.recorder
}

// CreateTokens mocks base method.
func (m *MockUserFacade) CreateTokens(ctx context.Context, user model.User) (facade.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTokens", ctx, user)
	ret0, _ := ret[0].(facade.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTokens indicates an expected call of CreateTokens.
func (mr *MockUserFacadeMockRecorder) CreateTokens(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTokens", reflect.TypeOf((*MockUserFacade)(nil).CreateTokens), ctx, user)
}

// DeleteUser mocks base method.
func (m *MockUserFacade) DeleteUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserFacadeMockRecorder) DeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserFacade)(nil).DeleteUser), ctx, userID)
}

// GoogleOAuth mocks base method.
func (m *MockUserFacade) GoogleOAuth(ctx context.Context, oauthID, email string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoogleOAuth", ctx, oauthID, email)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoogleOAuth indicates an expected call of GoogleOAuth.
func (mr *MockUserFacadeMockRecorder) GoogleOAuth(ctx, oauthID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoogleOAuth", reflect.TypeOf((*MockUserFacade)(nil).GoogleOAuth), ctx, oauthID, email)
}

// RefreshTokens mocks base method.
func (m *MockUserFacade) RefreshTokens(ctx context.Context, refreshTokenStr string) (facade.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", ctx, refreshTokenStr)
	ret0, _ := ret[0].(facade.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockUserFacadeMockRecorder) RefreshTokens(ctx, refreshTokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockUserFacade)(nil).RefreshTokens), ctx, refreshTokenStr)
}

// ResendVerificationEmail mocks base method.
func (m *MockUserFacade) ResendVerificationEmail(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendVerificationEmail", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResendVerificationEmail indicates an expected call of ResendVerificationEmail.
func (mr *MockUserFacadeMockRecorder) ResendVerificationEmail(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendVerificationEmail", reflect.TypeOf((*MockUserFacade)(nil).ResendVerificationEmail), ctx, userID)
}

// RevokeRefreshToken mocks base method.
func (m *MockUserFacade) RevokeRefreshToken(ctx context.Context, refreshTokenStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, refreshTokenStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockUserFacadeMockRecorder) RevokeRefreshToken(ctx, refreshTokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockUserFacade)(nil).RevokeRefreshToken), ctx, refreshTokenStr)
}

// SignIn mocks base method.
func (m *MockUserFacade) SignIn(ctx context.Context, username, password string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, username, password)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockUserFacadeMockRecorder) SignIn(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockUserFacade)(nil).SignIn), ctx, username, password)
}

// SignUp mocks base method.
func (m *MockUserFacade) SignUp(ctx context.Context, username, displayName, email, password string, isPublisher bool) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, username, displayName, email, password, isPublisher)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockUserFacadeMockRecorder) SignUp(ctx, username, displayName, email, password, isPublisher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockUserFacade)(nil).SignUp), ctx, username, displayName, email, password, isPublisher)
}

// UpdateUserProfile mocks base method.
func (m *MockUserFacade) UpdateUserProfile(ctx context.Context, userID string, params model.UpdateProfileParams) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, userID, params)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockUserFacadeMockRecorder) UpdateUserProfile(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockUserFacade)(nil).UpdateUserProfile), ctx, userID, params)
}

// ValidateAccessToken mocks base method.
func (m *MockUserFacade) ValidateAccessToken(tokenStr string) (auth.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenStr)
	ret0, _ := ret[0].(auth.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockUserFacadeMockRecorder) ValidateAccessToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockUserFacade)(nil).ValidateAccessToken), tokenStr)
}

// VerifyEmail mocks base method.
func (m *MockUserFacade) VerifyEmail(ctx context.Context, userID, code string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, userID, code)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockUserFacadeMockRecorder) VerifyEmail(ctx, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockUserFacade)(nil).VerifyEmail), ctx, userID, code)
}
