// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: authapi/v1/authapi.proto

package authapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthApiService_VerifyToken_FullMethodName = "/authapi.v1.AuthApiService/VerifyToken"
)

// AuthApiServiceClient is the client API for AuthApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthApiServiceClient interface {
	// VerifyToken verifies JWT access token
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
}

type authApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthApiServiceClient(cc grpc.ClientConnInterface) AuthApiServiceClient {
	return &authApiServiceClient{cc}
}

func (c *authApiServiceClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, AuthApiService_VerifyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthApiServiceServer is the server API for AuthApiService service.
// All implementations must embed UnimplementedAuthApiServiceServer
// for forward compatibility.
type AuthApiServiceServer interface {
	// VerifyToken verifies JWT access token
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
	mustEmbedUnimplementedAuthApiServiceServer()
}

// UnimplementedAuthApiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthApiServiceServer struct{}

func (UnimplementedAuthApiServiceServer) VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedAuthApiServiceServer) mustEmbedUnimplementedAuthApiServiceServer() {}
func (UnimplementedAuthApiServiceServer) testEmbeddedByValue()                        {}

// UnsafeAuthApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthApiServiceServer will
// result in compilation errors.
type UnsafeAuthApiServiceServer interface {
	mustEmbedUnimplementedAuthApiServiceServer()
}

func RegisterAuthApiServiceServer(s grpc.ServiceRegistrar, srv AuthApiServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthApiService_ServiceDesc, srv)
}

func _AuthApiService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthApiServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthApiService_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthApiServiceServer).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthApiService_ServiceDesc is the grpc.ServiceDesc for AuthApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authapi.v1.AuthApiService",
	HandlerType: (*AuthApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _AuthApiService_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authapi/v1/authapi.proto",
}
