name: "Test, build and push, deploy"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64

    - name: Run tests
      run: go test -race -vet=off ./...

  build_push_deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref_name == 'main' }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: asctod/game-library-auth:latest,asctod/game-library-auth:${{ github.sha }}

    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CLUSTER_CONFIG }}

    - name: Replace deployment variables
      run: |
        sed -i'' \
        -e 's/_K8S_URL_/${{ secrets.K8S_URL }}/g' \
        -e 's/_IMAGE_TAG_/${{ github.sha }}/g' \
        -e 's/_UI_URL_/${{ vars.UI_URL }}/g' \
        .k8s/*.yaml

    - name: Kubernetes Apply configs
      run: |
        kubectl apply -f .k8s/config.yaml
        kubectl apply -f .k8s/deployment.yaml
        kubectl apply -f .k8s/service.yaml
        kubectl apply -f .k8s/ingress.yaml
