name: "Test, build and push, deploy"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...

  build_push_deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref_name == 'main' }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: asctod/game-library-auth:latest,asctod/game-library-auth:${{ github.sha }}

    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CLUSTER_CONFIG }}

    - name: Replace deployment variables
      run: |
        sed -i'' -e 's/_K8S_URL_/${{ secrets.K8S_URL }}/g' -e 's/_IMAGE_TAG_/${{ github.sha }}/g' deploy/*.yaml

    - name: Kubernetes Apply configs
      run: | 
        kubectl apply -f deploy/config.yaml
        kubectl apply -f deploy/deployment.yaml
        kubectl apply -f deploy/service.yaml
        kubectl apply -f deploy/ingress.yaml
